# Generated by Django 4.1.5 on 2023-01-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50)),
                ('time', models.DateField()),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('tweet_text', models.TextField(max_length=1000)),
            ],
        ),
    ]
